### ISSUE TITLE
0.11 support

### ISSUE THREAD

**Issue by yoshuawuyts** [nodesource/docker-node-legacy#11]
Hi,

I was wondering if there's support (planned) for node v0.11. I couldn't find anything about it in the README or code. Thanks!

**Comment by wblankenship** [comment]
Final verdict: we will be following @chrislea's N|S PPA's. These do not include .11 but DO include .12 and iojs. The new images are [here](https://github.com/nodesource/docker-node) and already have these baked in as tags!
