### ISSUE TITLE
npm upgrade

### ISSUE THREAD

**Issue by rvagg** [nodesource/docker-node-legacy#12]
Docker are pinning to specific, recent versions of `npm` in their official Node.js images, see [here](https://github.com/docker-library/node/blob/51b1dd1984e287189106884c453ca506737eed78/0.10/Dockerfile#L20) for example. As of the next release they'll be putting npm@2.1.2 with each of their 0.8, 0.10 and 0.11 builds.

Currently we are just using the same version of npm that is bundled with the Node release that we're picking up from our deb & rpm distributions. We have the opportunity to do a similar thing to what Docker are doing and explicitly upgrade the version of npm we are distributing in our own nodesource/node Docker images.

Should we do this? If so, how do we determine what version of npm to pin to? How much more extensive do we need to make a test suite to test that this works (probably if we pull in these ideas: https://github.com/nodesource/distributions/pull/12#issuecomment-56770431 to the distro test script we could just pull that down and run inside the containers to test them).

@othiym23 your opinion here would be very helpful!

**Comment by wblankenship** [comment]
Migrating to new repo :beers:
