### ISSUE TITLE
Add git to the image to enable NPM to install private modules

### ISSUE THREAD

**Issue by wolfeidau** [nodesource/docker-node-legacy#17]
At the moment I add git.

```
RUN apt-get install -yy --no-install-recommends git
```

Prior to installing our software, would be handy to have it in the image as NPM sort of depends on it.

Otherwise awesome work.

**Comment by wolfeidau** [comment]
Thanks :wine_glass:

**Comment by wblankenship** [comment]
Moving this to the new images :beers:

**Comment by wolfeidau** [comment]
Fantastic thanks!
