### ISSUE TITLE
Documentation: Which version of node is installed?

### ISSUE THREAD

**Issue by rosskukulinski** [nodesource/docker-node-legacy#19]
This is touched on in #15, but I think the Docs should be updated as well.

It would be helpful to mention which version (or at least 0.10.x, 0.11.x) of NodeJS (and/or IOJS) you've installed. I looked throughout the README and couldn't find anything.

**Comment by wblankenship** [comment]
We are in the process of rebuilding the repository to explicitly state the version of node in the tag of the docker image on the registry. For now:

```
$ docker run -it --rm nodesource/node node -v
v0.10.32
$ docker run -it --rm nodesource/node npm --version
1.4.28
```

**Comment by wblankenship** [comment]
https://github.com/nodesource/docker-node now offers this
